### ISSUE TITLE
Config file name with multiple dots fails

### ISSUE THREAD

**Issue by norcino** [marazt/config-transformation#5]
I noticed that if you call the config file using multiple dots it fails to preview and apply the transformation.

**Working file names**
Web.ANYSTRING.config 
App.ANYSTRING.config 

**Not working**
Web.name.surname.config
App.any.string.config

**Expected behaviour**
Should not matter how many dots are in the file name.

**Comment by marazt** [comment]
Hi. Thanks for your feedback. I will check it. Or you can make a PR :)

**Comment by marazt** [comment]
Hi. I have finally time for inspection. Are you using just format **Web.FIRST.SECODS.config**, or shorter one, i.e., **Web.FIRST.config** too? What you can do, is to update plugin configuration (see attached image) to this regex: `([^.]+)\.([^.]+)\.(([^.]+)\.)?config`

This regex will accept both of file names. I hope it helps you.

![image](https://user-images.githubusercontent.com/323018/47616958-3d7ed400-dac3-11e8-984c-19ab3c8a59e5.png)

**Comment by norcino** [comment]
Thank you marazt, I will close the issue now.
