### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by QT07** [marazt/config-transformation#7]
Hi,

the extension cannot be installed in Visual Studio 2019 Professional.
I can only select Visual Studio 2017 Professional!

Can you please correct that?

Thank you!

**Comment by marazt** [comment]
Hi @QT07, I have tried it yesterday and I have no problem with VS 2019 (But I have Enterprise version only). And my colleagues have no problem to install it.
From the configuration, it should work.

`
<InstallationTarget Version="[11.0,17.0)" Id="Microsoft.VisualStudio.Pro"/>
`

I've double-checked [the migration post](https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/) too.

![image](https://user-images.githubusercontent.com/323018/55743743-640e4700-5a33-11e9-838c-3a6cffd2eb17.png)

Did you tried the new version **1.5.0.0**? 
I've tried to install it from both VS2019 Extension menu option and download it directly from VS Marketplace.

Please, @tbertenshaw , is it working for you?

**Comment by QT07** [comment]
Hi @tbertenshaw, thank you for the  answer!
In the meantime I have also adapted the configuration and now the installation works.
But the addon is moved to the deprecated folder because it is not loading asynchronously.
Are you planning on building this in the near future?

**Comment by marazt** [comment]
Hi @QT07 ,
It is good to hear that it is working. 
Yes, I saw that message about deprecated state and I'll update it. 
I hope it will go easy because the base project skeleton was originally running on VS2012.

**Comment by tbertenshaw** [comment]
i am unable to get it working currently with 2019 professional preview 5. See here https://developercommunity.visualstudio.com/content/problem/518105/extension-doesnt-appear-to-find-correct-target-vis.html
I don't understand why

**Comment by tbertenshaw** [comment]
ahh i know why/kind of. if you download the extension from the marketplace, rename the vsix extension to zip. Then edit the vsixmanifest

you see

 ```
<Installation InstalledByMsi="false" AllUsers="true">
    <InstallationTarget Version="[11.0,16.0)" Id="Microsoft.VisualStudio.Pro" />
    <InstallationTarget Version="[11.0,17.0)" Id="Microsoft.VisualStudio.Premium" />
    <InstallationTarget Version="[11.0,17.0)" Id="Microsoft.VisualStudio.Ultimate" />
    <InstallationTarget Version="[11.0,16.0)" Id="Microsoft.VisualStudio.Enterprise" />
    <InstallationTarget Version="[11.0,16.0)" Id="Microsoft.VisualStudio.Community" />
  </Installation>
```
not sure why this is the case however as thats not what is specified in the source.

**Comment by marazt** [comment]
> ahh i know why/kind of. if you download the extension from the marketplace, rename the vsix extension to zip. Then edit the vsixmanifest
> 
> you see
> 
> ```
> <Installation InstalledByMsi="false" AllUsers="true">
>    <InstallationTarget Version="[11.0,16.0)" Id="Microsoft.VisualStudio.Pro" />
>    <InstallationTarget Version="[11.0,17.0)" Id="Microsoft.VisualStudio.Premium" />
>    <InstallationTarget Version="[11.0,17.0)" Id="Microsoft.VisualStudio.Ultimate" />
>    <InstallationTarget Version="[11.0,16.0)" Id="Microsoft.VisualStudio.Enterprise" />
>    <InstallationTarget Version="[11.0,16.0)" Id="Microsoft.VisualStudio.Community" />
>  </Installation>
> ```
> not sure why this is the case however as thats not what is specified in the source.

Thanks! So it seems that it was build in some strange way and I don't understand why it was applied on some configurations only. So I'll build a new **vsix** today evening.

**Comment by tbertenshaw** [comment]
i get the same issue if i build the source locally, The bin folder contains the correct vsixmanifest, however the one in the bin folder's vsix(once unzipped) is the incorrect one. Wierd.

**Comment by marazt** [comment]
Hi @tbertenshaw , @QT07 . I have just published new version **1.5.1.0**.
So very interesting is a fact, that even I cleaned whole solution, removed **bin** and **obj** folders and rebuilt it again, in the **vsix**, there was changed version to **16** in some places as you described. So I've updated it manually.
Please, can you try it? 

Regards,

Marek

**Comment by tbertenshaw** [comment]
yeah that works for me 👍

**Comment by marazt** [comment]
Thanks a lot. So I'll close it and will check new versions if they have proper targets :).
